<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Events</h3>
            </div>
            <style>
                .sortable tr {
                    cursor: pointer;
                }
            </style>

            <div class="panel-body">
                <?php if (isset($events)) : ?>
                    <table class="table table-hover sortable">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nazwa wydarzenia</th>
                                <th>Adres</th>
                                <th>Autor</th>
                            </tr>
                        </thead>
                        <?php
                        foreach ($events as $event):
                            ?>
                            <tbody>
                                <tr class='click-link' data-href="events/view/<?php echo $event->getId() ?>">
                                    <td><?php echo $event->getId(); ?></td>
                                    <td><?php echo $event->getName(); ?></td>
                                    <td><?php echo $event->getAddress(); ?></td>
                                    <td><?php echo $event->getEmail(); ?></td>
                                </tr>
                            </tbody>
                        <?php endforeach; ?>
                    </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
