<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Events'); ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/favicon.ico'))
//                ->prependStylesheet($this->basePath() . '/css/style.css')
//                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet('https://bootswatch.com/flatly/bootstrap.min.css')
                ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js')
                ->prependFile($this->basePath() . '/js/respond.min.js',
                        'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js',
                        'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>
        <style>
            body { padding-top: 70px; };
            .sortable tr {
                cursor: pointer;
            }
        </style>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="mailto:piotr.a.kowalski@gmail.com?subject=Witaj na pokładzie!">Kowalski Piotr</a>
                </div>
                <div class="navbar-collapse collapse" id="searchbar">

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/events/add"><strong>Stwórz wydarzenie</strong></a></li>
                        <li><a href="/events"><strong>Lista wydarzeń</strong></a></li>
                    </ul>
                    <?php
                    $form = $this->searchForm;
                    $form->setAttribute('action',
                            $this->url('events', array('action' => 'index')));
                    $form->prepare();
                    ?>
                    <?php echo $this->form()->openTag($form); ?>

                    <div class="form-group" style="display:inline;">
                        <div class="input-group" style="display:table;">
                            <span class="input-group-addon" style="width:1%;">
                                <span class="glyphicon glyphicon-search"></span>

                            </span>
                            <?php echo $this->formRow($form->get('search')); ?>
                            <span class="input-group-btn">

                                <button class="btn btn-secondary click-link" type="button" data-href="events" >Wyczyść</button>

                            </span>
                        </div>
                    </div>
                    <?php echo $this->form()->closeTag(); ?>

                </div>
            </div>
        </div>


        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> Kowalski Piotr <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <script>
            jQuery(document).ready(function ($) {
                $(".click-link").click(function () {
                    window.document.location = $(this).data("href");
                });
            });
        </script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
